In [1]:
import turtle
import time
import numpy as np
import random

In [2]:
wn = turtle.Screen()
wn.bgcolor("black")
wn.setup(width=600,height=600)
wn.title("Line Plot")
wn.tracer(0)

In [3]:
#creating drawing pen
pen = turtle.Turtle()
pen.hideturtle()
pen.speed(0)
pen.pensize(3)

In [4]:
def plotDot(pen,coDic):
    pen.color("red")
    pen.setheading(0)
    pen.pensize(4)
    for ii,jj in coDic:
        pen.penup()
        pen.goto(ii,jj)

        pen.pendown()
        pen.dot()
    

In [89]:
def drawLine(l,pen,angle,x,y):
    pen.pensize(2)
    pen.up()
    pen.goto(x,y)    
    pen.color("green")
    pen.setheading(180)
    pen.rt(angle)
    pen.pendown()
    pen.fd(l)
    pen.bk(2*l)
    pen.fd(l)


In [504]:
def distList(ii,ang,tempo):
    distList = []
    slopeOffset = [-1,0,1]
    slope = np.tan(1*np.pi-ii*np.pi/180-ang)
    if slope == 0:
        slope = 0.000000001
    sData = slope+1/slope
#     slopeTu = np.sin(1*np.pi-ii*np.pi/180-ang)
    slopeTu = np.cos(1*np.pi-ii*np.pi/180-ang)
#     slopeTu = np.sqrt(1+np.square(1/slope)) 
    for jj in slopeOffset:
        #working
        xPrime = (tempo[:,[1]]+1/slope*tempo[:,[0]]-1*jj*slopeTu)/sData
        yPrime = slope*(xPrime)+(jj*slopeTu)
#         xPrime = (tempo[:,[1]]+1/slope*tempo[:,[0]]-1*jj*slopeTu)/sData
#         yPrime = slope*(xPrime)+(jj*slopeTu)
        dist = np.sqrt(np.square(xPrime-tempo[:,[0]])+np.square(yPrime-tempo[:,[1]]))
        dist = dist.round(1)
        distList.append(dist)
    return np.array(distList)

In [505]:
temp = np.array([[160,50],[0,0],[100,100],[0,100],[100,5]])
# numb = 10
# temp = np.random.randint(-150,150,[numb,2])
# temp = np.array([[-200,200],[-150,78],[0,0],[100,100],[-100,100],[100,-150]])
temp

array([[160,  50],
       [  0,   0],
       [100, 100],
       [  0, 100],
       [100,   5]])

In [506]:
tempo = temp
tempo = tempo-tempo[0,:]
index = np.array([0])
x,y = temp[index,:][0]
indList=[np.zeros([1]),np.zeros([1])]
count = 0
ang = 0
prvInd = 0
lastInd = 0
indKyu =[np.zeros([1,2]),np.zeros([1,2])] 
for _ in range(1):
    for ii in np.arange(38,42,0.5):
        drawLine(600,pen,ii,x,y)
        plotDot(pen,temp.tolist())
        wn.update()
        time.sleep(0.005)
        pen.clear()
        dist = distList(ii,ang,tempo)
        offsetSum = np.sum(dist[[0,2],:],axis=0)
        theta = np.array(offsetSum-offsetSum[index])
        theta = theta.round(1)
        indFind = np.where(theta <= 1)[0]
        print(ii)
        print(dist)

#         if len(indFind)>=2 and np.abs(ii-lastInd) >= 3.0:
#             print(ii,'in-condition')
#             lastInd = ii
#             indNxt = np.where(indFind != index)
# #             print(tempo[indFind[indNxt]])
#             index = indFind[indNxt]
#             if len(index) > 1:
#                 print('2 index')
#                 ll= np.where(theta[index] == np.min(theta[index]))[0]
#                 index = index[ll]
#             indList.append(index)
# #             print(indList,len(indList))
#             aa = indList.pop(0)
#             if aa == index:
#                 print('continue')
#                 continue
# #             print(indList,len(indList),aa)
#             x,y = temp[index,:][0]
# #             print(tempo[index,:][0])
#             tempo = tempo-tempo[index,:]
# #             ang += np.pi
            
#             print(ii,index)
#             print(temp[index,:][0])
            
        print('-------------')



38.0
[[[   0.6]
  [ 138.5]
  [   1.8]
  [  59.7]
  [  73. ]]

 [[   0. ]
  [ 137.9]
  [   2.5]
  [  59.1]
  [  72.4]]

 [[   0.6]
  [ 137.3]
  [   3.1]
  [  58.5]
  [  71.8]]]
-------------
38.5
[[[   0.6]
  [ 139.3]
  [   1.2]
  [  61.1]
  [  73.2]]

 [[   0. ]
  [ 138.7]
  [   1.8]
  [  60.5]
  [  72.6]]

 [[   0.6]
  [ 138.1]
  [   2.4]
  [  59.9]
  [  72. ]]]
-------------
39.0
[[[   0.6]
  [ 140.2]
  [   0.5]
  [  62.4]
  [  73.3]]

 [[   0. ]
  [ 139.5]
  [   1.1]
  [  61.8]
  [  72.7]]

 [[   0.6]
  [ 138.9]
  [   1.7]
  [  61.2]
  [  72.1]]]
-------------
39.5
[[[   0.6]
  [ 140.9]
  [   0.2]
  [  63.8]
  [  73.5]]

 [[   0. ]
  [ 140.4]
  [   0.4]
  [  63.2]
  [  72.9]]

 [[   0.6]
  [ 139.8]
  [   1. ]
  [  62.6]
  [  72.3]]]
-------------
40.0
[[[   0.6]
  [ 141.7]
  [   0.9]
  [  65.1]
  [  73.6]]

 [[   0. ]
  [ 141.1]
  [   0.3]
  [  64.5]
  [  73. ]]

 [[   0.6]
  [ 140.6]
  [   0.3]
  [  64. ]
  [  72.5]]]
-------------
40.5
[[[   0.6]
  [ 142.5]
  [   1.5]
  [  66.5]
 

In [465]:
ll= np.where(theta[index] == np.min(theta[index]))[0]
ll

array([0])

In [453]:
index

array([1, 3])

In [358]:
temp

array([[-200,  200],
       [-150,   78],
       [   0,    0],
       [ 100,  100],
       [-100,  100],
       [ 100, -150]])

In [277]:
theta = offsetSum-offsetSum[index]
i,j = np.where( theta==np.min(theta[np.nonzero(theta)]))
print(i,j)

[4] [0]


In [424]:
aa = [np.zeros(1),np.zeros(1)]

In [425]:
aa.pop(0)

array([ 0.])

In [ ]:
yy = np.array(tempo[:,[1]],dtype=float)
xx = np.array(tempo[:,[0]],dtype=float)
zz = np.divide(yy,xx,out=np.zeros_like(yy),where=xx !=0)
zz

In [147]:
cc = np.array([])
cc

array([], dtype=float64)

In [ ]:
# temp = np.array([[160,50],[0,0],[100,100],[0,100],[100,5]])
# # temp = np.random.randint(-150,150,[8,2])
# temp = np.array([[-200,200],[3,78],[0,0],[100,100],[-100,100],[100,-150]])
# temp

In [ ]:
def slopeCounter(index,coDic):
    tempo = coDic
    slope = -np.tan(index*np.pi/180)#np.tan(2*np.pi*(180+index)/360)
    if slope == 0:
        slope = 0.000000001
    sData = slope+1/slope
    xPrime = (tempo[:,[1]]+1/slope*tempo[:,[0]])/sData
    yPrime = slope*xPrime
    dist = np.sqrt(np.square(xPrime)+np.square(yPrime))
    dist = dist.round(2)
    sortDist = np.sort(dist,axis=0)
#     print(sortDist)
    ind = np.where(dist == sortDist[1])[0]
    return dist,sortDist[1],ind,slope

In [ ]:
tempo = temp
tempo = tempo-tempo[0,:]
index = 1
indPre = slopeCounter(index,tempo)
x,y = temp[index,:]
count = np.array([0,0])
indKyu =[np.zeros([1,2]),np.zeros([1,2])] 
tempCount = 0
for _ in range(1):
    for ii in np.arange(0, 47, 0.5):
        drawLine(600,pen,ii,x,y)
        plotDot(pen,temp.tolist())
        wn.update()
        time.sleep(0.005)
        pen.clear()
        distM,dist,ind,slope = slopeCounter(ii,tempo)
#         print(ind.view())
        if len(ind) == 2:
            print('boom')
            inx = np.where(ind.view() != indPre)[0]
            ind = ind[inx]
            x,y = temp[ind,:][0]
            tempo = tempo - tempo[ind,:][0]
        print(ii,ind.view(),x,y)
#             if dist.item() <=0.5:
#                 print('tt')
#                 x,y = temp[ind,:][0]
#                 tempo = tempo - tempo[ind,:][0]
#         indPre = ind
#         xx,yy = tempo[ind,:][0]
#         print(ii,dist,ind)

#         print(ii,tempo[index,:],dist,tempo[ind,:][0],slope)
        prevInd = ind
# #         prevSlope = 

In [ ]:
for ii in np.arange(0, 2, 0.5):
    slope = np.tan(ii*np.pi/180)
    print(ii,slope)

In [ ]:
type(ind)

In [ ]:
wn.mainloop()

In [ ]:
i,j = np.where( theta==np.min(theta[np.nonzero(theta)]))

In [ ]:
preX

In [ ]:
aa.append(temp[1,:])

In [ ]:
kk = aa.pop(0)

In [ ]:
#         print(ii)
#         print(np.sum(dist[[0,2],:],axis=0))
#         print('************')
#         print(dist[1])
#         print('------------')

In [ ]:
#         if pp == 1:
#             print(ii,indFind)
#         print(ii)
# #         print(dist[:,2])
#         print(theta.round(1))
#         print('--------')
#         i,j = np.where( theta==np.min(theta[np.nonzero(theta)]))
#         print(ii,i,theta[i],offsetSum[i],index)
#         indFind = np.where(offsetSum == offsetSum[index])[0]

In [ ]:
#         print(dist)
#         if x >= 0: # positive x-axix
#             if y >= 0:  
#         print(indMax)
#         print(tempo[indMax])
#         print('*****')
#         print(indMin)
#         print(tempo[indMin])
# # #         indClose = np.min(dist[np.nonzero(dist)])
# # #         print(indClose)
# #         print('----')
#         print(dist[indMin])
# #         print(-slope*tempo[:,[0]]+tempo[:,[1]])
# #         print(dist[indMax])
# #         print(dist[indMin])
#         print('--------')
#         if ff.view() <= 0.5:
#             yy = np.array(tempo[:,[1]],dtype=float)
#             xx = np.array(tempo[:,[0]],dtype=float)
# #             zz = np.divide(xx,yy,out=np.zeros_like(xx),where=yy !=0)
#             zz = np.divide(yy,xx,out=np.zeros_like(yy),where=xx !=0)
# #             zz = np.tan(np.pi-zz*np.pi/180)
#             print(ii,slope)
#             print(zz)
#             print(dist)
#         tt = np.divide(tempo[])
#         print(np.min([0.5,ff.view()]))
#         if ii - lastInd != 0.5:
#             if len(ind) >= 2 or ff.view() <= 0.5 :
#                 print(ii,'in loop')
#                 tempInd = index
#                 if len(ind) >= 2:
#                     index = np.where(ind != index)[0]
#                     index = ind[index]
#                 else:
#                     print('dd')
#                     index = ind
#                 if len(index) >= 2:
#                     ee = np.where(index == np.min(index))
#                     index = index[ee]
#                 print(ind,index)
#                 if index != prvInd:
#                     tempo = tempo-tempo[index,:][0]
#                     x,y = temp[index,:][0]
#                     if preX != x and preY != y:
#                         ang += np.pi
#                         lastInd = ii
#                         print('zzz')
#                     print('yo')
#                     prvInd = index
# #                 lastInd = ii
#                 preX = x
#                 preY = y
            

In [ ]:
#         slope = np.tan(1*np.pi/2+ii*np.pi/180-ang)
#         if slope == 0:
#             slope = 0.000000001
#         sData = slope+1/slope
#         xPrime = (tempo[:,[1]]+1/slope*tempo[:,[0]])/sData
#         yPrime = slope*xPrime
#         dist = np.sqrt(np.square(xPrime)+np.square(yPrime))
#         dist = dist.round(2)
#         print(ii,slope)
#         ff = np.sort(dist,axis=0)
#         ff = ff[1]
#         ind = np.where(dist <= np.min([0.5,ff.view()]))[0]
# #         print(ii,slope,180-ii,sData,ff)
#         yy = np.array(tempo[:,[1]],dtype=float)
#         xx = np.array(tempo[:,[0]],dtype=float)
#         zz = np.divide(yy,xx,out=np.zeros_like(yy),where=xx !=0)
#         print(ii,slope,ff)
#         print(dist)
#         print('--------')
#         indMax = [jj for jj in range(len(zz)) if yy[jj] >= zz[jj] and yy[jj] != 0 and zz[jj] != 0]
#         indMin = [jj for jj in range(len(zz)) if yy[jj] < zz[jj]]
#         print(ii,slope,ff,actualSlope)
#         print('above_________________')
#         print(indMax,dist[indMax])
#         print('below_________________')
#         print(indMin,dist[indMin])
#         print('-----------------')